services:
  database:
    image: postgres:14
    environment:
      POSTGRES_DB: urlshortener
      POSTGRES_USER: "${DB_USER}"       
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
volumes:
  postgres-data: